config/routes.rb
FundApp::Application.routes.draw do
  get "pages/home"

  get "pages/apply"

  get "pages/faq"

  get "pages/about"

  get "pages/profiles"

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def apply
  end

  def faq
  end

  def about
  end

  def profiles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom footer">
		<div class="navbar-inner">
		<div class="container">
		  <ul class="nav pull-left">
		  	<li><%= link_to 'Next deadline: September 8, 2014', pages_apply_path %></li>
		  </ul> 
		  <ul class="nav pull-right">
		  	<li><a href="https://www.mountainschool.org/podium/default.aspx?t=1300" target="_blank">Alumni Directory</a>
		    <li><a href="https://www.facebook.com/pages/The-Mountain-School-of-Milton-Academy/252084468164123" target="_blank">Facebook</a>
		    <li><a href="http://www.linkedin.com/groups?gid=150431&trk=group-name" target="_blank">LinkedIn</a>
		    <li><a href="https://twitter.com/MountainSchool" target="_blank">Twitter</a>
		  </ul>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <li class="active brand">
          <%= link_to "Garden Hill Fund", root_path %>
        </li>
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "FAQ", pages_faq_path %></li>
        <li><%= link_to "Committee", pages_profiles_path %></li>
        <li><a href="/Garden_Hill_Fund_Grants_October_2013.pdf">2013 Grants</a>
        <li><%= link_to "Apply", pages_apply_path %> </li>
      </ul>
      <ul class="nav pull-right">
        <li>
          <a href="https://www.mountainschool.org/podium/default.aspx", target="_blank"><%= image_tag("/images/TMS_Logo.png", :height => '49.6', :width => '110.4', :alt => "TMS Alumni Site") %></a>
        </li>
      </ul>

      <% if false %> <!-- currently commented out -->
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to "My Trips", user_trips_path(current_user) %></li>
            <li><%= link_to "Account", edit_user_registration_path(current_user) %></li>
            <li><%= button_to('Sign out', destroy_user_session_path, :method => :delete) %><li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garden Hill Fund of The Mountain School</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>

	<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>A Mission-Based Program:</h1> <br /><br />

The Garden Hill Fund is a response to two missions.  The first is the mission of the Mountain School itself:  <em>The Mountain School cultivates a diverse and interdependent community of scholars who learn to know a place and take care of it.  Through collaborative learning and shared work, students emerge from their semester prepared to reach beyond the self and focus on the common good.</em> <br /><br />

Implicit in this mission is that it is realized in the adult lives of the school’s graduates, in their ongoing and various efforts to “reach beyond the self and focus on the common good.” <br /><br />

The second is the mission of the Mountain School Alumni Initiative: <em>The Mission of the Mountain School Alumni Initiative is to support a dynamic community of Mountain School graduates by connecting them to each other and helping them carry forward the intellectual curiosity, celebration of place and commitment to service we associate with the Mountain School.</em> <br /><br />

Thus the processes and systems of the Fund are designed to connect Mountain Schoolers across the generations, and give them opportunities to know about and support each other’s good work.  (Current students will be part of the process of reading and rating proposals.) <br /><br />

Mountain School graduates may apply to the Alumni Committee for GRANTS of up to $10,000, or MINI-GRANTS of up to $1000 for projects that benefit “the common good” in a range of ways.  Click <%= link_to "here", pages_apply_path %> to apply.<br /><br />

The Alumni Committee does not want the guidelines for the first year of the Garden Hill Fund to be overly restrictive, because we view this first round of grants as a learning opportunity for us.  That said, we are looking to fund proposals that meet much of the following criteria:<br />
•	Creative responses to the Mission of the school and the spirit of the alumni initiative.  (We would like to fund a diversity of projects.)<br />
•	Projects that have a clear positive impact on other people<br />
•	Tangible results within a reasonably short time span<br />
•	Skill-building in the graduate, which can be used in further endeavors<br />
•	Lean and realistic project budgets <br />
•	Ongoing impact of the project when possible<br /><br />

Examples might be:<br />
•	A college summer of service;<br />
•	A “big idea” from a recent college graduate who needs some seed money to investigate it;<br />
•	A community-based project that exemplifies the idea of “knowing and caring for a place,” brought by a graduate who volunteers time and expertise where he or she lives;<br />
•	A new program in the civic sector that needs seed money, brought by a graduate who has a leadership role in a non-profit organization<br /><br />

But we are open to other creative responses to the two missions.<br /><br />

app/views/pages/apply.html.erb
<h1>How To Apply:</h1> <br />

<% if true %>
	<%= button_to "Download the Proposal Form", "/GardenHillFund_Application_20130714.docx", :method => :get %>
<% end %><br>

Complete the application form and email it to <a href="mailto:GardenHillFund@mountainschool.org?Subject=Garden%20Hill%20Fund%20Inquiry", target="_blank">GardenHillFund@mountainschool.org</a><br><br>

<strong>Deadlines for Proposals:</strong><br />
<p>
There will be two rounds of grant-making in the 2014-15 academic year, so students in both the fall and spring semesters can participate in the reading and ranking of proposals.
</p>

<p>
The first deadline is September 8th, with notification of awards in November. The second deadline is February 9th, with notification in April.
</p>

<p>
We expect to award a total of $45,000 in these two cycles.
</p>

<strong>Questions?</strong><br />

Please refer to the document <%= link_to "Frequently Asked Questions", pages_faq_path %><br />

<p> You may direct any other questions via email to:  <a href="mailto:GardenHillFund@mountainschool.org?Subject=Garden%20Hill%20Fund%20Inquiry", target="_blank">GardenHillFund@mountainschool.org</a> </p>


<!-- <iframe src="https://docs.google.com/forms/d/1r-ci2Qy4ThYP7MvaOa_GjpFIdk1KU1tflP2Ps9_FQlE/viewform?embedded=true" width="800" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe> -->

app/views/pages/faq.html.erb
<h1>Frequently Asked Questions</h1>
<div id="faq-list">
	<div class="question">
		Q: How do I apply?
	</div>
	<div class="answer">
<strong>A:</strong> An on-line application form is under development and will be operational in early August, 2014, in time for the fall, 2014 round of Garden Hill Fund grants.
	</div><br>

	<div class="question">
		Q: What is the timing for applying?
	</div>
	<div class="answer">
<p>
<strong>A:</strong> There will be two rounds of grant-making in the 2014-15 academic year, so students in both the fall and spring semesters can participate in the reading and ranking of proposals.
</p>

<p>
The first deadline is September 8th, with notification of awards in November. The second deadline is February 9th, with notification in April.
</p>

<p>
We expect to award a total of $45,000 in these two cycles.
</p>

	</div><br>

	<div class="question">
		Q: What size grants are available?
	</div>
	<div class="answer">
		<strong>A:</strong> There are two types of grants available: <br>
		&nbsp&nbsp■	Mini-Grant: up to $1,000, or <br>
		&nbsp&nbsp■	Garden Hill Grant: between $2,000-10,000 <br>
	Each application should address the rationale for the specific grant amount.	<br>
	Since we will have a limited amount of money to award in grants, the Committee WILL consider partial funding in some cases. If you are asking for a large grant, it will be helpful to know how partial funding would affect your proposed project.
	</div><br>

	<div class="question">
		Q: Who will decide which projects receive funding?
	</div>
	<div class="answer">
		<strong>A:</strong> The Alumni Committee will make the grants, with input from a selection of Mountain School students, faculty, and donors.  Visit <a href="http://gardenhillfund.org">http://gardenhillfund.org</a> for a description of the evaluation process.
	</div><br>

	<div class="question">
		Q: How do I donate to the Garden Hill Fund?
	</div>
	<div class="answer">
		<strong>A:</strong> The first year pilot has been made possible by the generous gifts of 10 graduates, ranging from Spring ‘85 to Spring ‘97.  In the future we plan to develop a more formalized process for raising additional funds in order to continue to make grants.  If you are interested in learning more about donating to the fund, please contact us at <a href="mailto:GardenHillFund@mountainschool.org?Subject=Garden%20Hill%20Fund%20Application", target="_blank">GardenHillFund@mountainschool.org</a> or reach out to <a href="mailto:davidandnancy.grant@mountainschool.org?Subject=Garden%20Hill%20Fund%20Application", target="_blank">David or Nancy Grant (davidandnancy.grant@mountainschool.org)</a>.
	</div><br>

	<div class="question">
		Q: What if I have more questions?
	</div>
	<div class="answer">
		<strong>A:</strong>Please send us a note at <a href="mailto:GardenHillFund@mountainschool.org?Subject=Garden%20Hill%20Fund%20Application", target="_blank">GardenHillFund@mountainschool.org</a> and we will get back to you ASAP.  Alternatively, feel free to reach out to <a href="mailto:davidandnancy.grant@mountainschool.org?Subject=Garden%20Hill%20Fund%20Application", target="_blank">David or Nancy Grant (davidandnancy.grant@mountainschool.org</a>.
	</div><br>

	<div class="question">
		Q: If I am awarded a grant, what will be expected of me?
	</div>
	<div class="answer">
		<strong>A:</strong> 
		All grant recipients will be asked to report back to the Alumni Committee within one year to describe their project outcomes or progress to date. Project questionnaires and profiles of funded and completed projects will be posted at <a href="http://gardenhillfund.org">www.gardenhillfund.org</a>. <br>
		Recipients of Garden Hill Grants ($2,000-$10,000) will also be asked to choose one additional way to share their experience with the Mountain School community. This could include:<br>
		&nbsp&nbsp&nbsp○		a short feature article for the Mountain School Alumni Newsletter<br>
		&nbsp&nbsp&nbsp○		a video or documentary <br>
		&nbsp&nbsp&nbsp○		a presentation or participation in a panel at an Alumni event, or at the Mountain School<br>
		&nbsp&nbsp&nbsp○		a blog  <br>
		&nbsp&nbsp&nbsp○		other creative ideas are welcomed!
	</div><br>	




</div>

app/views/pages/home.html.erb
<h1>The Garden Hill Fund: Cultivating the Common Good</h1> <br />

<p>
The Garden Hill Fund is a program of the Mountain School Alumni Initiative.  Grants from the Fund support the good work of Mountain School graduates of all ages as they bring to life the mission of the school -- to reach beyond the self and focus on the common good -- in their own communities and the larger world.
</p>

<p>
<b>Background:</b> In a survey of Mountain School graduates in 2012, the idea of creating a mechanism that would allow the school’s graduates to support each other’s good work in the world was widely endorsed. 82% of respondents said they would consider contributing to such a fund, and 53% said they would consider applying to it! The only caution expressed repeatedly was that the new fund should not decrease donations to the Mountain School’s Annual Fund.  In 2013, ten graduates, ranging from Spring ’85 to Spring ’97, made generous gifts of $5000 each in order to launch the new Fund, which the Alumni Committee decided to name after the Mountain School’s iconic landmark and symbol of growth, community, and aspiration: Garden Hill.
</p>

<p>
The first two rounds of grants were announced in October, 2013 and April, 2014, after a selection process that involved not only a committee of graduates but also significant input from current students.
</p>

<%= image_tag("/images/GardenHillBuckets.png", :height => '820', :width => '2000', :alt => "Garden Hill") %>

app/views/pages/profiles.html.erb
<div>
	<div><h1>Meet the Alumni Committee</h1></div>

	<div id="committte-intro">
	</div><br>

	<div class="container">
		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Steve Lee, f91</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Steve.png", :alt => "Steve") %>
				</div>
				<div id="profile-text">
					I am an editor and speechwriter for a financial services firm. I live in Brooklyn with my wife, Carolyn, and our son, Miles. 
				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Frank Gorke, f93</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Frank.png", :alt => "Frank") %>
				</div>
				<div id="profile-text">
					I live outside Boston with my wife and daughter. Until recently I oversaw energy efficiency policy and programs for the Commonwealth of Massachusetts. I am now opening a northeast office for a fast-growing energy efficiency consulting company. I  keep stumbling upon TMS alums in my work and social life, and have long thought, "Wouldn't it be great if we found each other on purpose, rather than by accident?"
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Ben Pomeroy, s95</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Ben.png", :alt => "Ben") %>
				</div>
				<div id="profile-text">
					I live in Brooklyn, NY and my spend days writing mainly about food and cooking. TMS has always been a pillar for personal growth for me, and my semester friends are some of my closest. For those reasons and the promise of farm inspired feasts, I am excited to help expand and strengthen the TMS global community.

				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Schuyler Daum, f06</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Schuyler.png", :alt => "Schuyler") %>
				</div>
				<div id="profile-text">
					I am about to graduate from Harvard with a degree in the Classics, but I'll be staying in Boston next year to work in consulting. I got involved with this new TMS alumni initiative because Alden's English class is still the best class I've taken and I'd like to spread that TMS thoughtfulness to the world outside Vershire.
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Megan McJennett, f89</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Megan.png", :alt => "Megan") %>
				</div>
				<div id="profile-text">
					I live in Seattle with my husband and 2 young children and am the Programs Director for a local youth development nonprofit. About 15 years after I left Garden Hill it finally dawned on me that the experience had been a pivotal moment in my life and I noticed that every time I met a bunch of TMS grads I always really enjoyed them, so when the opportunity came up to help shape this new initiative, I jumped at the chance to get involved.
				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Jake Upton, s88</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Jake.png", :alt => "Jake") %>
				</div>
				<div id="profile-text">
					I live outside of Boston with my wife and three kids.  There years ago I founded Upton + Partners, LLC to develop uniquely innovative real estate projects that have the prospect of contributing special social values to our communities. Our projects have ranged from tented eco-resorts on the pristine Northern California coast, to renovating world class museums and redeveloping dilapidated historic mills into LEED-certified loft housing in the urban core. I wanted to get involved in this effort because the world is catching on to the Mountain School’s teachings/values and I believe there is an increasing need for alumni to have a platform to support each other in our unique pursuits.
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Simon Taranto, f04</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/simon.png", :alt => "Simon") %>
				</div>
				<div id="profile-text">
					I live in Boulder, CO and work with a start up software company focused on the energy sector.  I enjoy mountain biking, skiing, and playing rugby.  I jumped at the chance to get involved with the TMS alumni network because I missed the Northeast and Vermont.  I look forward to getting back in touch with old friends and making new connections with TMS alumni.
				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Anna (Lee) Fogelsong, f96</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Anna.png", :alt => "Anna") %>
				</div>
				<div id="profile-text">
					I currently live in San Francisco with my husband and new baby girl and work on energy efficiency and climate change issues for Pacific Gas & Electric Company. My time at The Mountain School transformed me, challenged me, and gave me some great friends (not to mention the fudgy oat squares!), and I hope to continue that journey as a TMS alum. 
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Jim Sherwin, s00</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Jim.png", :alt => "Jim") %>
				</div>
				<div id="profile-text">
					I am a Cleveland native who now lives in New York and works for JSTOR, a digital archive of academic journals. I joined the TMS alumni committee to help all alumni reconnect with former classmates and make new connections with members of the vast TMS community.
				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Sidra Smith, s87</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Sidra.png", :alt => "Sidra") %>
				</div>
				<div id="profile-text">
					I serve as academic dean at the Cambridge School of Weston in Massachusetts, having worked 20 years as a teacher and administrator at the middle school, high school and college levels. I believe my experiences as a TMS student led me to pursue a career in education along with scholarly interests in eco-literary criticism. An African American urban dweller with roots in the deep South, I don't see myself as a prototypical TMS alum. 
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Marie Horbar, f03</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Marie.png", :alt => "Marie") %>
				</div>
				<div id="profile-text">
					I am a native Vermonter and currently live in Washington D.C. where I work for the U.S. Institute for Environmental Conflict Resolution, a program of the Udall Foundation. D.C. life is wonderful, in large part thanks to the Mountain School community in this city.  I am extremely excited about the new alumni initiative and look forward to working with all of you to create something meaningful, lasting, and fun!
				</div>
			</div>
			<div class="span5" id="profile">
				<div id="profile-name">Cassie Marlantes Rahm, s97</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Cassie.png", :alt => "Cassie") %>
				</div>
				<div id="profile-text">
					I live in New York and work as a lawyer for the Natural Resources Defense Council. I was excited to join this initiative because I love all things Mountain School and it sounded like a wonderful idea to bring more alums together and figure out ways to bring home the fun of the Mountain School.
				</div>
			</div>
		</div><br>

		<div class="row">
			<div class="span5" id="profile">
				<div id="profile-name">Liza Walker, f87</div>
				<div id="profile-photo">
					<%= image_tag("/images/profiles/Liza.png", :alt => "Liza") %>
				</div>
				<div id="profile-text">
					I live an hour away from TMS, in Waitsfield, Vermont, with my husband and two kids. For the past fifteen years, I have been working for the Vermont Land Trust, helping families and communities protect farm and forestland that we and future generations will need-- for growing local food, making syrup, hiking, skiing, learning, and keeping natural systems intact.  I was excited to join the TMS alumni committee to have an opportunity to reconnect with others who were impacted by their time at the school and to think about how we can bring the experience forward into our current lives and communities! 
				</div>
			</div>
			<div class="span5" id="profile">

			</div>
		</div>

	</div>
</div>